import React, { useState } from 'react';
import { Shield, Lock, Eye, FileText, Users, Globe, Database, AlertCircle, CheckCircle2, ChevronDown, ChevronUp } from 'lucide-react';

export default function PrivacyPolicy() {
  const [expandedSection, setExpandedSection] = useState(null);

  const toggleSection = (index) => {
    setExpandedSection(expandedSection === index ? null : index);
  };

  const sections = [
    {
      id: 1,
      title: "General",
      icon: <Shield className="w-6 h-6" />,
      subsections: [
        {
          title: "Electronic Sound",
          content: "This document was electronically created by use of the information Technology Act, 2008 and its associated provisions pertaining to electronic records. It is generated by a computer system and doesn't require physical or digital signatures."
        },
        {
          title: "Compliance",
          content: "This Policy is published in compliance with the provisions of the Information Technology (Intermediaries guidelines) Rule, 2011 which mandates publishing privacy policies for website access and usage."
        },
        {
          title: "Website Disclaimer and Terms of Use",
          content: "The domain name www.maxpinegroup.in (\"Website\") is owned and operated by Maxpine Group. Maxpine Group includes Axis Pai Ltd, a Company incorporated under the laws of India, having its corporate office at New Delhi. Please carefully read this Privacy Policy prior to using this Website or to access any material, information or services through this Website. This Privacy Policy does not apply to information about you collected by affiliates or third parties that may post links or advertisements on or otherwise interact with this Website."
        }
      ]
    },
    {
      id: 2,
      title: "Collection of Personal and Other Information",
      icon: <Database className="w-6 h-6" />,
      subsections: [
        {
          title: "Information We Collect",
          content: "Maxpine Group collects information when you visit our Website, including registration, information about your preferences, and engagement with our services. We may collect personal information such as name, email, phone number, and other details you provide."
        },
        {
          title: "Cookies and Tracking",
          content: "We use cookies and similar tracking technologies to enhance your experience, analyze site traffic, and understand user behavior. You can control cookie preferences through your browser settings."
        }
      ]
    },
    {
      id: 3,
      title: "Use of Personal Information",
      icon: <Users className="w-6 h-6" />,
      subsections: [
        {
          title: "How We Use Your Information",
          content: "We use the information to provide services to you, improve our website, personalize your experience, and respond to your inquiries. We may also use it to send you updates about our services and promotional content with your consent."
        },
        {
          title: "Data Protection",
          content: "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction."
        }
      ]
    },
    {
      id: 4,
      title: "Disclosure of Personal Information",
      icon: <Eye className="w-6 h-6" />,
      subsections: [
        {
          title: "Third Party Sharing",
          content: "We may share your information with trusted third parties who assist us in operating our website, conducting our business, or servicing you. These parties are obligated to keep your information confidential."
        },
        {
          title: "Legal Requirements",
          content: "We may disclose your information when required by law or in response to valid requests by public authorities."
        }
      ]
    },
    {
      id: 5,
      title: "Security",
      icon: <Lock className="w-6 h-6" />,
      subsections: [
        {
          title: "Data Security Measures",
          content: "Transmission of the Website are secure and protected. Any information posted on the User when transmitting to the Website is encrypted to prevent the information from being accessed by unauthorized individuals. The User is solely responsible for keeping his/her password and Account information confidential."
        }
      ]
    },
    {
      id: 6,
      title: "User's Consent",
      icon: <CheckCircle2 className="w-6 h-6" />,
      subsections: [
        {
          title: "Consent to Policy",
          content: "By using the Website, users are providing information to the Company through the Website. You consent to the collection and use of the information disclosed by you on the Website in accordance with this Policy. If you don't agree to this Policy, please do not use the Website."
        }
      ]
    },
    {
      id: 7,
      title: "Grievance Officer",
      icon: <AlertCircle className="w-6 h-6" />,
      subsections: [
        {
          title: "Contact Information",
          content: "In case you have any grievance regarding the usage of your personal information or wish to exercise your rights under this policy, please contact our Grievance Officer."
        }
      ]
    },
    {
      id: 8,
      title: "Dispute Resolution and Jurisdiction",
      icon: <Globe className="w-6 h-6" />,
      subsections: [
        {
          title: "Governing Law",
          content: "If you choose to access the Website from locations other than India, you will be responsible for compliance with local laws if and to the extent local laws are applicable. This Privacy Policy is governed by the laws, rules, and regulations of India."
        }
      ]
    }
  ];

  const quickLinks = [
    "Information We Collect",
    "How We Use Your Data",
    "Data Security",
    "Your Rights",
    "Contact Us"
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
      {/* Breadcrumb */}
      <div className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center text-sm text-gray-600">
            <span className="hover:text-[#3c92a9] cursor-pointer">Home</span>
            <span className="mx-2">/</span>
            <span className="text-gray-900 font-medium">Privacy Policy</span>
          </div>
        </div>
      </div>

      {/* Hero Section */}
      <div className="relative bg-gradient-to-r from-[#3c92a9] via-[#2c7d94] to-[#2692b0] text-white py-16 sm:py-20 overflow-hidden">
        <div className="absolute inset-0 bg-black opacity-10"></div>
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-gradient-to-br from-transparent via-transparent to-black opacity-20"></div>
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="flex justify-center mb-6">
              <div className="bg-white text-[gray] bg-opacity-20 backdrop-blur-sm rounded-full p-4">
                <Shield className="w-12 h-12" />
              </div>
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-4">
              Privacy Policy
            </h1>
            <p className="text-xl text-blue-50 max-w-3xl mx-auto">
              Your privacy is important to us. Learn how we collect, use, and protect your information.
            </p>
            <div className="mt-8 flex items-center justify-center gap-2 text-sm text-blue-100">
              <FileText className="w-4 h-4" />
              <span>Last Updated: January 2025</span>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-16">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          {/* Sidebar - Quick Navigation */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-2xl p-6 shadow-lg border border-gray-100 sticky top-8">
              <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                <FileText className="w-5 h-5 text-blue-600" />
                Quick Navigation
              </h3>
              <div className="space-y-2">
                {sections.map((section) => (
                  <a
                    key={section.id}
                    href={`#section-${section.id}`}
                    className="block text-sm text-gray-600 hover:text-blue-600 hover:bg-blue-50 px-3 py-2 rounded-lg transition-colors"
                  >
                    {section.title}
                  </a>
                ))}
              </div>

              <div className="mt-8 pt-6 border-t border-gray-200">
                <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <AlertCircle className="w-5 h-5 text-[#3c92a9] flex-shrink-0 mt-0.5" />
                    <div>
                      <h4 className="font-semibold text-gray-900 text-sm mb-1">Need Help?</h4>
                      <p className="text-xs text-gray-600 mb-3">Contact our privacy team for any questions</p>
                      <button className="text-xs bg-[#3c92a9] text-white px-3 py-1.5 rounded-lg hover:bg-[#217d96] transition-colors">
                        Contact Us
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-3">
            {/* Introduction */}
            <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-8 mb-8 border border-blue-100">
              <div className="flex items-start gap-4">
                <div className="bg-[#3c92a9] text-white p-3 rounded-lg">
                  <Shield className="w-6 h-6" />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-3">Our Commitment to Your Privacy</h2>
                  <p className="text-gray-700 leading-relaxed">
                    At Maxpine Group, we are committed to protecting your privacy and ensuring the security of your personal information. 
                    This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website 
                    <span className="font-semibold text-[#3c92a9]"> www.maxpinegroup.in</span>.
                  </p>
                </div>
              </div>
            </div>

            {/* Policy Sections */}
            <div className="space-y-6">
              {sections.map((section, index) => (
                <div 
                  key={section.id} 
                  id={`section-${section.id}`}
                  className="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden"
                >
                  <button
                    onClick={() => toggleSection(index)}
                    className="w-full px-6 py-5 flex items-center justify-between hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex items-center gap-4">
                      <div className="bg-gradient-to-br from-blue-100 to-indigo-100 p-3 rounded-lg text-[#3c92a9]">
                        {section.icon}
                      </div>
                      <div className="text-left">
                        <h3 className="text-xl font-bold text-gray-900">{section.id}. {section.title}</h3>
                        <p className="text-sm text-gray-500 mt-1">{section.subsections.length} subsection(s)</p>
                      </div>
                    </div>
                    {expandedSection === index ? (
                      <ChevronUp className="w-6 h-6 text-gray-400" />
                    ) : (
                      <ChevronDown className="w-6 h-6 text-gray-400" />
                    )}
                  </button>

                  {expandedSection === index && (
                    <div className="px-6 pb-6 space-y-6 border-t border-gray-100 pt-6">
                      {section.subsections.map((subsection, subIndex) => (
                        <div key={subIndex} className="bg-gray-50 rounded-xl p-6">
                          <h4 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                            <div className="w-2 h-2 bg-[#3c92a9] rounded-full"></div>
                            {subsection.title}
                          </h4>
                          <p className="text-gray-700 leading-relaxed text-sm pl-4">
                            {subsection.content}
                          </p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Important Notice */}
            <div className="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-8 mt-8 border border-amber-200">
              <div className="flex items-start gap-4">
                <AlertCircle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-1" />
                <div>
                  <h3 className="text-xl font-bold text-gray-900 mb-3">Important Notice</h3>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    By using our website, you acknowledge that you have read and understood this Privacy Policy and agree to be bound by its terms. 
                    If you do not agree with any part of this policy, please do not use our website.
                  </p>
                  <p className="text-sm text-gray-600">
                    This policy is subject to change without prior notice. We recommend reviewing this page periodically for any updates.
                  </p>
                </div>
              </div>
            </div>

            {/* Contact Section */}
            <div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 mt-8 text-white">
              <h3 className="text-2xl font-bold mb-4">Have Questions About Your Privacy?</h3>
              <p className="text-gray-300 mb-6">
                If you have any questions, concerns, or requests regarding this Privacy Policy or how we handle your personal information, 
                please don't hesitate to reach out to our privacy team.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <button className="bg-white text-gray-900 px-6 py-3 rounded-lg font-semibold hover:bg-gray-100 transition-all">
                  Contact Privacy Team
                </button>
                <button className="bg-transparent border-2 border-white text-white px-6 py-3 rounded-lg font-semibold hover:bg-white hover:text-gray-900 transition-all">
                  Download PDF
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer CTA */}
      <div className="bg-gradient-to-r from-[#3c92a9] via-[#257990] to-[#1f748b] py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold text-white mb-4">
            Your Trust Matters to Us
          </h2>
          <p className="text-blue-50 text-lg mb-8 max-w-2xl mx-auto">
            We are committed to maintaining the highest standards of privacy and data protection
          </p>
          <div className="flex flex-wrap justify-center gap-6 text-white">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5" />
              <span>Secure Data Handling</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5" />
              <span>Transparent Practices</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5" />
              <span>User Control</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}